ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: "contour"
    contour.heptio.com/retry-on: "5xx"
    contour.heptio.com/num-retries: "5"
    contour.heptio.com/request-timeout: "15s"
    contour.heptio.com/per-try-timeout: "3000"
  hosts:
    - host: dev.happytravel.com
      paths: [/]

  tls: 
    - hosts:
        - dev.happytravel.com